### ISSUE TITLE
yubikey-manager fails to build with Python 3.9: imports abc from collections 

### ISSUE THREAD

**Issue by gbcox** [Yubico/yubikey-manager#308]
Fedora bugzilla here:  https://bugzilla.redhat.com/show_bug.cgi?id=1793489

Fedora will be switching to Python 3.9 for Fedora 33 (Approximately, October 2020).  The early testing with Python 3.9 uncovered incompatibility as follows.

Text from report:

yubikey-manager fails to build with Python 3.9.0a2.

ImportError: Failed to import test module: test_generate_cert_and_csr
Traceback (most recent call last):
  File "/usr/lib64/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/builddir/build/BUILD/yubikey-manager-1f22620b623c6b345dd9f9193ec765a542dddc80/test/on_yubikey/cli_piv/test_generate_cert_and_csr.py", line 7, in <module>
    from ..framework import cli_test_suite, yubikey_conditions
  File "/builddir/build/BUILD/yubikey-manager-1f22620b623c6b345dd9f9193ec765a542dddc80/test/on_yubikey/framework/__init__.py", line 6, in <module>
    import test.util
  File "/builddir/build/BUILD/yubikey-manager-1f22620b623c6b345dd9f9193ec765a542dddc80/test/util.py", line 2, in <module>
    from ykman.cli.__main__ import cli
  File "/builddir/build/BUILD/yubikey-manager-1f22620b623c6b345dd9f9193ec765a542dddc80/ykman/cli/__main__.py", line 41, in <module>
    from .util import UpperCaseChoice, YkmanContextObject
  File "/builddir/build/BUILD/yubikey-manager-1f22620b623c6b345dd9f9193ec765a542dddc80/ykman/cli/util.py", line 34, in <module>
    from collections import OrderedDict, MutableMapping
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/lib64/python3.9/collections/__init__.py)

See https://docs.python.org/3.9/whatsnew/3.9.html#removed

"The abstract base classes in collections.abc no longer are exposed in the regular collections module. This will help create a clearer distinction between the concrete classes and the abstract base classes."

For the build logs, see:
https://copr-be.cloud.fedoraproject.org/results/@python/python3.9/fedora-rawhide-x86_64/01170202-yubikey-manager/

For all our attempts to build yubikey-manager with Python 3.9, see:
https://copr.fedorainfracloud.org/coprs/g/python/python3.9/package/yubikey-manager/

Testing and mass rebuild of packages is happening in copr. You can follow these instructions to test locally in mock if your package builds with Python 3.9:
https://copr.fedorainfracloud.org/coprs/g/python/python3.9/

Let us know here if you have any questions.

Python 3.9 will be included in Fedora 33. To make that update smoother, we're building Fedora packages with early pre-releases of Python 3.9.
A build failure prevents us from testing all dependent packages (transitive [Build]Requires), so if this package is required a lot, it's important for us to get it fixed soon.

**Comment by dagheyman** [comment]
Thanks for the report! We'll look into adding support for Python 3.9.

**Comment by kfken** [comment]
This affects Debian Testing branch (bullseye) because it uses python 3.9.  While attempting to apt install I get:

`
Unpacking python3-yubikey-manager (3.1.2~ppa4~xenial1) over (3.1.1-3) ...
dpkg: error processing archive /var/cache/apt/archives/python3-yubikey-manager_3.1.2~ppa4~xenial1_all.deb (--unpack):
 trying to overwrite '/usr/lib/python3/dist-packages/ykman/native/ykpers.py', which is also in package python3-ykman 3.1.1-3`
Errors were encountered while processing:
 /var/cache/apt/archives/python3-yubikey-manager_3.1.2~ppa4~xenial1_all.deb
needrestart is being skipped since dpkg has failed
`

**Comment by dainnilsson** [comment]
@kfken This doesn't look related to Python 3.9 (the original issue with the collections module has been postponed until Python 3.10, so ykman should work fine under 3.9).

Based on the  error log it looks like you are mixing .deb packages from different sources, which aren't compatible with each other. A package for Ubuntu Xenial shouldn't be used on Debian at all.

**Comment by kfken** [comment]
@dainnilsson - I wondered about xenial being in the apt list, but I've always had that and it worked up until this latest update.  I tried re-doing the setup instructions the ppa and ended up with the same yubico.list file.  Is that because it's the default when it can't determine Ubuntu version (because I don't have one)?

What would be the correct `deb` entry for Debian Testing?  `groovy`?  `bionic`?

**Comment by dainnilsson** [comment]
Debian has its own packaging of yubikey-manager, which is not provided by Yubico. This is the `python3-ykman` package which is conflicting with the one you're trying to install. The PPA packages we provide are for Ubuntu only, they are not expected to work on Debian. Since you already seem to have `python3-ykman` installed there should be no need to add any additional packages.

**Comment by dainnilsson** [comment]
The import has been fixed in ykman 4.0.
