### ISSUE TITLE
ykman piv reset fails under version 5.0.0

### ISSUE THREAD

**Issue by eporama** [Yubico/yubikey-manager#524]
- YubiKey Manager (ykman) version: 5.0.0
- How was it installed?: homebrew update
- Operating system and version: Mac OS Monterey version 12.6
- YubiKey model and version: Device type: YubiKey 5Ci FIPS (and others)
- Bug description summary:
```
ykman piv reset
```
throws python errors

Steps to reproduce
---
```
$ ykman piv reset
ERROR: An unexpected error has occuredTraceback (most recent call last):
  File "/opt/homebrew/Cellar/ykman/5.0.0/libexec/lib/python3.10/site-packages/ykman/_cli/__main__.py", line 364, in main
    cli(obj={})
  File "/opt/homebrew/Cellar/ykman/5.0.0/libexec/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Cellar/ykman/5.0.0/libexec/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Cellar/ykman/5.0.0/libexec/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Cellar/ykman/5.0.0/libexec/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Cellar/ykman/5.0.0/libexec/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Cellar/ykman/5.0.0/libexec/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/Cellar/ykman/5.0.0/libexec/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/homebrew/Cellar/ykman/5.0.0/libexec/lib/python3.10/site-packages/ykman/_cli/piv.py", line 221, in reset
    force or click.confirm(
TypeError: confirm() got an unexpected keyword argument 'prompt'
```

Expected result
---
```
$ ykman piv reset

WARNING! This will delete all stored PIV data and restore factory settings. Proceed? [y/N]: y
Resetting PIV data...
Success! All PIV data have been cleared from the YubiKey.
Your YubiKey now has the default PIN, PUK and Management Key:
	PIN:	<redact>
	PUK:	<redact>
	Management Key:	<redact>
```

I confirmed that this worked in 4.0.9

**Comment by eporama** [comment]
I believe that [this commit](https://github.com/Yubico/yubikey-manager/commit/1b5bbeda82265ac4f1b7b6b9e00b6b4010257d60) introduced the issue with `click.confirm` that the first argument should simply be the string.

```
    force or click.confirm(
        "WARNING! This will delete all stored PIV data and restore factory "
        "settings. Proceed?",
        abort=True,
        err=True,
    )
``` 

without the `prompt=`.

**Comment by dainnilsson** [comment]
Thanks! The PR has been merged, and we'll be putting out a 5.0.1 to include this fix.

**Comment by briantully** [comment]
Any update or an ETA on when 5.0.1 will be released to resolve this bug?

**Comment by dainnilsson** [comment]
Now fixed in 5.0.1.
