### ISSUE TITLE
Updating yubikey-manager affects yubioath-desktop

### ISSUE THREAD

**Issue by infosec-handbook** [Yubico/yubikey-manager#89]
Under Arch (4.15.14-1-ARCH), I run yubikey-manager 0.4.6 and yubioath-desktop without problems.

When I update yubikey-manager to 0.5.0 or 0.6.0, yubioath-desktop shows "No YubiKey detected". Console output is:

```
Got library name:  "/usr/lib/qt/qml/io/thp/pyotherside/libpyothersideplugin.so"
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc:///py/yubikey.py\", line 11, in <module>\n    from ykman.util import (\n\nImportError: cannot import name 'derive_key'\n"
qml: Cannot import module: yubikey (Traceback (most recent call last):

  File "qrc:///py/yubikey.py", line 11, in <module>
    from ykman.util import (

ImportError: cannot import name 'derive_key'
)
```

**Comment by dagheyman** [comment]
Thanks for the report. We don't maintain the arch packages, so I suggest to file a report to the arch maintainers. There was however [some mistakes](https://github.com/Yubico/yubioath-desktop/issues/261) made on our part when releasing yubikey-manager 0.4.6, so that could definitely be related and we'll try to be more careful with dependencies in the future.
